name: ulendo_workspace
packages:
  - apps/*
  - packages/*

scripts:
  run:rider:
    run: cd apps/rider_app && flutter run
    description: Run the Rider App locally.
  run:driver:
    run: cd apps/driver_app && flutter run
    description: Run the Driver App locally.
