// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEib4eB_DZ_ij0ih2B7PzHcFFoVpN7J-4',
    appId: '1:110852320623:android:89a8a8c9277c124e9f8c9a',
    messagingSenderId: '110852320623',
    projectId: 'ulendo-dev',
    databaseURL: 'https://ulendo-dev-default-rtdb.firebaseio.com',
    storageBucket: 'ulendo-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKvkXlukY-37ZL3VB4ThJwhM06r7dU_ZE',
    appId: '1:110852320623:ios:47f6ddb805e9c4e19f8c9a',
    messagingSenderId: '110852320623',
    projectId: 'ulendo-dev',
    databaseURL: 'https://ulendo-dev-default-rtdb.firebaseio.com',
    storageBucket: 'ulendo-dev.firebasestorage.app',
    iosBundleId: 'mw.ulendo.riderApp',
  );
}
